### ISSUE TITLE
Cannot load pre-trained word vectors

### ISSUE THREAD

**Issue by liefra** [mayabot/mynlp#22]
I tried to load a [pre-trained word vector](https://fasttext.cc/docs/en/english-vectors.html), but receive the following error: `Caused by: java.lang.IllegalArgumentException: Unknown LossName enum second :774911284`

I load the model with:
``` val model =   FastText.loadModelFromSingleFile(File("/Users/liefra/crawl-300d-2M.vec"))```

Is this an issue, or just me doing it wrong?

**Comment by jimichan** [comment]
SingleFile is one Java Model File used by fasttext4j.
maybe you can use    `FastText.loadCppModel ` load bin mode file from Fasttext 
https://dl.fbaipublicfiles.com/fasttext/vectors-crawl/cc.en.300.bin.gz
(unzip it before load )

**Comment by liefra** [comment]
Thank you very much for your super fast reply :)

Yes, it works when I load it with the bin format:
`val model =   FastText.loadCppModel(File("/Users/liefra/cc.en.300.bin"))`
