### ISSUE TITLE
训练出来的模型能不能整合成一个文件？

### ISSUE THREAD

**Issue by codelast** [mayabot/mynlp#24]
训练出来的模型有4个文件：

> args.bin
> dict.bin
> input.matrix
> output.matrix

load 模型的时候，load 的是这4个文件所在的目录，这4个文件缺一不可。这样在单机使用的情况下没什么问题。
现在我想把这个模型放到一个 Map-Reduce job 中加载，这时就需要把4个模型整合成一个文件放到 distributed cache 中。
4个文件有没有办法整合成一个文件？
谢谢。

**Comment by jimichan** [comment]
能的，最新版本的里面有这个api，可以保存到单体文件



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Darran Zhang <notifications@github.com&gt;
发送时间: 2020年7月24日 15:22
收件人: mayabot/mynlp <mynlp@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[mayabot/mynlp] 训练出来的模型能不能整合成一个文件？ (#24)

**Comment by jimichan** [comment]
/**
     * 保存文件到单一文件
     */
    fun saveModelToSingleFile(file: File) {
        if (!file.exists()) {
            file.createNewFile()
        }
        assert(file.isFile)
 
        file.outputStream().channel.use { channel -&gt;
            args.save(channel)
            dict.save(channel)
 
            channel.writeBoolean(input is QuantMatrix)
            channel.writeBoolean(output is QuantMatrix)
 
            input.save(channel)
            output.save(channel)
 
        }
    }


发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Darran Zhang <notifications@github.com&gt;
发送时间: 2020年7月24日 15:22
收件人: mayabot/mynlp <mynlp@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[mayabot/mynlp] 训练出来的模型能不能整合成一个文件？ (#24)

**Comment by codelast** [comment]
@jimichan 感谢回复。给出的代码好像是Kotlin的？有Java的示例吗？thanks

**Comment by codelast** [comment]
另外，如果合并成了一个文件，在加载模型的时候，还是用一样的方法来加载吗？

`FastText model = FastText.Companion.loadModel(new File("/path/to/model"), false);`

这里的 /path/to/model 原来使用的是4个模型文件所在的目录，如果合并成了一个文件，是否要改成使用那个文件的路径（或者还是使用目录）？
