### ISSUE TITLE
NullException  com.mayabot.nlp.segment.core.CoreDictionary#path not found

### ISSUE THREAD

**Issue by liushan150** [mayabot/mynlp#3]
![image](https://user-images.githubusercontent.com/17740907/50512410-b5ba4380-0acc-11e9-8d3f-486bb9538f1c.png)

**Comment by jimichan** [comment]
这些新修改的代码，相关的资源还在我本地，这几天度假中，我找时间发布到maven仓库中，虽然我觉得新的资源还不是非常完美，以后通过版本迭代更新资源

**Comment by jimichan** [comment]
@liushan150 你更新最新的代码，现在资源发布到cdn上面了，运行程序可以自动下载
