### ISSUE TITLE
RuntimeException

### ISSUE THREAD

**Issue by asd821300801** [mayabot/mynlp#5]
java.lang.RuntimeException: java.io.IOException: Unable to create parent directories of /.mynlp.data/caches

**Comment by jimichan** [comment]
你是运行的最新master分支？

**Comment by asd821300801** [comment]
2.0.0版本的

**Comment by jimichan** [comment]
.mynlp.data 文件夹默认是在当前用户目录下的，这个 /.mynlp.data/caches是根目录？
