### ISSUE TITLE
不要再发送垃圾邮件了！

### ISSUE THREAD

**Issue by jrfeng** [mayabot/mynlp#7]
不要再发送垃圾邮件！我已经连续收到两封了，如果真的要推广，可以去技术论坛发帖，掘金、CSDN 等各种技术论坛都行。你可以把这个库的功能、实现原理、使用方法等都发一遍，感兴趣的自然会 start。发送垃圾邮件就真的过分了，直接印象减分，反而起到反作用。

**Comment by jimichan** [comment]
感谢建议，
项目是个好项目，如果了解一个好的分词架构的话，建议研究代码
，代码精简易读，
另外真没时间写各类文章，就随便搞了
爬虫抓mail地址，有一部分名单发了两次，统计错误。
邮件发送效果还是不错的，47%的打开率，
应该算是推广邮件吧，垃圾邮件也谈不上。
PS：哪位有流量资源联系我一下，帮忙推广一下
各位也可以帮我在blog上写写评测，给我一些反馈。
使用的场景和需求多了，会让mynlp越来越好。

主要是gmail的垃圾邮件判断太厉害了，也有
可能是测试导致的。

如果还有的话，请把那个发送邮箱拉黑！
