### ISSUE TITLE
有没有Fat jar提供？

### ISSUE THREAD

**Issue by pymudou** [mayabot/mynlp#9]
虽然是分模块，但是没有集成基础包

**Comment by jimichan** [comment]
?不理解？
什么是基础包

**Comment by pymudou** [comment]
不好意思，是我觉得在使用人名识别的时候会还会依赖其他外包，不止一个，其他模块的也会添加，是原本设计是这样的还是人名识别涉及到其他模块，对于内网封闭的环境确实不是很友好，我最后的方案是hanklp，虽然就一个包，但是其他功能有点臃肿7.8M，在使用咱们的mynlp-all 还是需要一些其他的东西，有点看不懂。所以就自己以为对其他非标准包的依赖过强，给你添麻烦，不好意思。

**Comment by jimichan** [comment]
没啥不好意思的，你是说最好只依赖一个JAR包是吧
其实可以使用Gralde的shadow插件，把相关依赖打到一个包（FAT）里面去？
我考虑如何写wiki，运行命令直接在本地打FAT JAR，方便内网封闭环境使用
你这个提议很实用

**Comment by jimichan** [comment]
打开这个地址 [https://github.com/mayabot/mynlp-package](https://github.com/mayabot/mynlp-package)，
里面详细说明了如果制作FAT包

**Comment by waynerQiu** [comment]
请问一下 7.x 版本的插件什么时候放出啊？

**Comment by jimichan** [comment]
现在的版本去除了guava依赖和guice依赖，默认引入mynlp.jar就会包含基本功能
